runtime: nodejs20
env: standard

instance_class: F1

automatic_scaling:
  target_cpu_utilization: 0.65
  min_instances: 0
  max_instances: 10

env_variables:
  ARANGO_URL: "http://34.173.53.216:8529/"
  ARANGO_DB_NAME: "data-generator-db"
  ARANGO_USERNAME: "root"
  ARANGO_PASSWORD: "yz50W9xXN4IJX0BF"
  GROQ_API_KEY: "gsk_CCXCPjMDuKKO04HpofSuWGdyb3FY0srd42rxli8VquEOCN1VWvMgg"
  ANTHROPIC_API_KEY: "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"
  PASSCODE: "gigstrap-ai-passcode"
